---
- hosts: ubuntu
  user: ansible
  become: yes
  tasks:
    - name: update and install java
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present
    - name: install docker
      ansible.builtin.apt:
        name: docker.io
        state: present
        update_cache: yes
    - name: add group
      ansible.builtin.user:
        name: "ansible"
        group: "docker"
        append: yes
    - name: Pull an image
      community.docker.docker_image:
        name: alpine
        tag: latest
        source: pull
        pull:
          platform: amd64
    - name: Log into DockerHub
      community.docker.docker_login:
        username: suvitha
        password: Sugasuvi@123
    - name: Tag and sh to docker hub
      community.docker.docker_image:
        name: alpine
        tag: latest
        repository: suvitha/alpine:latest
        push: true
        source: local
