---
- hosts: ubuntu
  user: ansible
  become: yes
  vars:
    keys: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    repos: 'deb http://pkg.jenkins.io/debian-stable binary/'
  tasks:
    - name: update and install java
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present
    - name: update and maven java
      ansible.builtin.apt:
        name: maven
        update_cache: yes
        state: present
   - name: update and install tomcat
      ansible.builtin.apt:
        name: tomcat
        update_cache: yes
        state: present
   - name: mvn install
      ansible.builtin.apt:
        name: docker.io
        state: present
        update_cache: yes
    - name: add group
      ansible.builtin.user:
        name: "ansible"
        group: "docker"
        append: yes
  - name: Add an Apt signing key, uses whichever key is at the URL
      ansible.builtin.apt_key:
        url: "{{keys}}"
        state: present
    - name: somerepo | apt source
      ansible.builtin.apt_repository:
        repo: "{{repos}}"
        update_cache: yes
        state: present
    - name: update and install jenkins
      ansible.builtin.apt:
        name: jenkins
        update_cache: yes
        state: present
      when:
        - ansible_facts['distribution'] == "Ubuntu"
        - ansible_facts['distribution_major_version'] == "22"
        
