---
- hosts: ubuntu
  user: ansible
  become: yes
  vars:
    keys: https://packages.grafana.com/gpg.key
    repos: "deb https://packages.grafana.com/oss/deb stable main"
 tasks:
    - name: Add an Apt signing key, uses whichever key is at the URL
      ansible.builtin.apt_key:
        url: "{{keys}}"
        state: present
    - name: somerepo | apt source
      ansible.builtin.apt_repository:
        repo: "{{repos}}"
        update_cache: yes
        state: present 
    - name: update and install grafana
      ansible.builtin.apt:
        name: grafana
        update_cache: yes
        state: present
     - name: start grafana server
      ansible.builtin.systemd_service:
        name: grafana-server
        state: started
    - name: enable grafana server
      ansible.builtin.systemd_service:
        name: grafana-server
        enabled: true
