---
- hosts: ubuntu
  user: ansible
  become: yes
  tasks:
    - name: update and install java
      ansible.builtin.apt:
        name: openjdk-8-jdk
        update_cache: yes
        state: present
        
