---
- hosts: ubuntu
  user: ansible
  become: yes
  vars:
    tomurl:  https://downloads.apache.org/tomcat/tomcat-X.Y.Z.tar.gz
  tasks:
    - name: Download tomcat url
      ansible.builtin.apt_key:
        url: "{{tomurl}}"
        state: present
    - name: Extract tomacat
      ansible.builtin.unarchive:
        src: apache-tomcat-X.Y.Z.tar.gz
        dest: /opt/tomcat
    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /opt/tomcat/
        owner: tomcat
        group: tomcat
        mode: '700'
    - name: Add a user to tomcat-users.xml
      ansible.builtin.lineinfile:
        path: /opt/tomcat/conf/tomcat-users.xml
        regexp: '<tomcat-users>'  # Look for a line containing '<tomcat-users>'
        line: '  <user username="admin" password="aadmin" roles="manager-gui,admin-gui,manager-script"/>'  # Add the user line
        insertafter: '<tomcat-users>'
    - name: update and install jenkins
      ansible.builtin.apt:
        name: jenkins
        update_cache: yes
        state: present
    when:
        - ansible_facts['distribution'] == "Ubuntu"
        - ansible_facts['distribution_major_version'] == "18"
