---
- hosts: ubuntu
  user: ansible
  become: yes
  vars:
    tomurl: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.83/bin/apache-tomcat-9.0.83.tar.gz
  tasks:
    - name: Add Tomcat User
      ansible.builtin.user:
        name: tomcat
        home: /opt/tomcat
        shell: /bin/false
        system: yes
    - name: Extract tomacat
      ansible.builtin.unarchive:
        src: '{{tomurl}}'
        dest: /opt/tomcat
    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /opt/tomcat/conf
        owner: tomcat
        group: tomcat
        mode: '755'
    - name: Add a user to tomcat-users.xml
      ansible.builtin.lineinfile:
        path: /opt/tomcat/conf/tomcat-users.xml
        regexp: 'tomcat-users'  
        line: 'user username="admin" password="aadmin" roles="manager-gui,admin-gui,manager-script"' 
        insertafter: 'tomcat-users'
     - name: comment the context.xml
      ansible.builtin.replace:
        path: /opt/tomcat/conf/server.xml
        regexp: '<Valve className="org.apache.catalina.valves.RemoteAddrValve" allow="127\.\d+\.\d+\.\d+|::1|0:0:0:0:0:0:0:1" />'
        replace: '<!--  <Valve className="org.apache.catalina.valves.RemoteAddrValve" allow="127\.\d+\.\d+\.\d+|::1|0:0:0:0:0:0:0:1" /> -->'
    - name: reload tomcat
      ansible.builtin.systemd_service:
        state: restarted
        daemon_reload: true
        name: tomcat9
    - name: Start Tomcat service
      ansible.builtin.systemd_service:
        name: tomcat9  
        state: started
    
