---
- hosts: ubuntu
  user: ansible
  become: yes
  vars:
    tomurl:  https://downloads.apache.org/tomcat/tomcat-X.Y.Z.tar.gz
  tasks:
    - name: Download tomcat url
      ansible.builtin.apt_key:
        url: "{{tomurl}}"
        state: present
    - name: Extract tomacat
      ansible.builtin.unarchive:
        src: apache-tomcat-X.Y.Z.tar.gz
        dest: /opt/tomcat
    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /opt/tomcat/
        owner: tomcat
        group: tomcat
        mode: '700'
    - name: Edit port number in server
      ansible.builtin.replace:
        path: /opt/tomcat/conf/server.xml
        regexp: '8080'
        replace: '9090'
    - name: Add a user to tomcat-users.xml
      ansible.builtin.lineinfile:
        path: /opt/tomcat/conf/tomcat-users.xml
        regexp: 'tomcat-users'  
        line: 'user username="admin" password="aadmin" roles="manager-gui,admin-gui,manager-script"' 
        insertafter: 'tomcat-users'
     - name: comment the context.xml
      ansible.builtin.replace:
        path: /opt/tomcat/conf/server.xml
        regexp: '<Valve className="org.apache.catalina.valves.RemoteAddrValve" allow="127\.\d+\.\d+\.\d+|::1|0:0:0:0:0:0:0:1" />'
        replace: '<!--  <Valve className="org.apache.catalina.valves.RemoteAddrValve" allow="127\.\d+\.\d+\.\d+|::1|0:0:0:0:0:0:0:1" /> -->'
    - name: reload tomcat
      ansible.builtin.systemd_service:
        state: restarted
        daemon_reload: true
        name: tomcat9
    - name: Start Tomcat service
      ansible.builtin.systemd_service:
        name: tomcat9  
        state: started
    
