---
- hosts: ubuntu
  user: ansible
  become: yes
  vars:
    tomurl: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.83/bin/apache-tomcat-9.0.83.tar.gz
  tasks:
    - name: update and install java
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present
    - name: update and install tomcat
      ansible.builtin.group:
        name: tomcat
        state: present
    - name: Add Tomcat User
      ansible.builtin.user:
        name: tomcat
        home: /opt/tomcat
        shell: /bin/false
        system: yes
        create_home: yes
    - name: Extract tomacat
      ansible.builtin.unarchive:
        src: '{{tomurl}}'
        remote_src: yes
        dest: /opt/tomcat
    - name: create a symbolic link
      ansible.builtin.file:
        src: apache-tomcat-9.0.83
        dest: /opt/tomcat/latest 
        state: link
    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /opt/tomcat
        owner: tomcat
        group: tomcat
        recurse: yes
        mode: 0755
    - name: Set execute permission on Tomcat scripts
      command: sudo sh -c 'chmod +x /opt/tomcat/apache-tomcat-9.0.83/bin/*.sh'
    - name: create systemd unit file
      ansible.builtin.copy:
        src: tomcat.service
        dest: /etc/systemd/system/tomcat.service
        owner: tomcat
        group: tomcat
    - name: Add a user to tomcat-users.xml
      ansible.builtin.copy:
        src: tomcat-users.xml
        dest: /opt/tomcat/latest/conf/tomcat-users.xml
        owner: tomcat
        group: tomcat
    - name: add permission 
      ansible.builtin.copy:
        src: context.xml
        dest: /opt/tomcat/latest/webapps/manager/META-INF/context.xml
        owner: tomcat
        group: tomcat
    - name: create systemd unit file
      ansible.builtin.copy:
        src: context.xml
        dest: /opt/tomcat/latest/webapps/host-manager/META-INF/context.xml
        owner: tomcat
        group: tomcat
    - name: reload tomcat
      ansible.builtin.systemd_service:
        state: restarted
        daemon_reload: true
        name: tomcat
    - name: Start Tomcat service
      ansible.builtin.systemd_service:
        name: tomcat
        state: started
